/**
 * Browser-side compiler worker: wraps the browsercc fork (clang/lld in WASM)
 * behind the exact interface apps/web uses today for server compiles.
 *
 * Interface parity with POST /api/compile:
 *   input:  { source: string }
 *   output: { objBase64: string }          (x64 COFF object, real clang bytes)
 *
 * The worker owns its clang instance (reused across jobs) inside a
 * DedicatedWorkerGlobalScope; the main thread talks to it via transferable
 * messages. Falls back to reporting upstream stderr verbatim on errors.
 */

/// <reference lib="webworker" />

let clangMod = null;
let lldMod = null;

const DIST_URL = new URL("../../vendor/browsercc/dist/", import.meta.url);
const SYSROOT_URL = new URL("sysroot.tar", DIST_URL);

async function getModules() {
  if (!clangMod || !lldMod) {
    // Specifiers are computed at runtime so bundlers cannot statically
    // resolve them — a missing (not-yet-built) vendor/browsercc/dist must
    // degrade to the caller's server-compile fallback, never break the
    // dev-server transform of this worker.
    const clangSpec = new URL("clang.js", DIST_URL).href;
    const lldSpec = new URL("lld.js", DIST_URL).href;
    const [{ default: Clang }, { default: LLD }] = await Promise.all([
      import(/* webpackIgnore: true */ /* @vite-ignore */ clangSpec),
      import(/* webpackIgnore: true */ /* @vite-ignore */ lldSpec),
    ]);
    let stderr = "";
    clangMod = await Clang({
      thisProgram: "clang",
      printErr: (s) => { stderr += s + "\n"; },
    });
    lldMod = await LLD({ thisProgram: "ld.lld", printErr: () => {} });
    void stderr;
  }
  return { clangMod, lldMod };
}

async function loadSysrootInto(mod) {
  const tarBuf = await (await fetch(SYSROOT_URL)).arrayBuffer();
  const dec = new TextDecoder();
  const u8 = new Uint8Array(tarBuf);
  let off = 0;
  while (off + 512 <= u8.length) {
    const hdr = u8.slice(off, off + 512);
    const name = dec.decode(hdr.slice(0, 100)).replace(/\0.*$/, "");
    if (!name) break;
    const size = parseInt(dec.decode(hdr.slice(124, 136)).replace(/\0.*$/, "").trim(), 8) || 0;
    const contentStart = off + 512;
    if (size > 0 && !name.endsWith("/")) {
      const dir = name.split("/").slice(0, -1).join("/");
      if (dir && !mod.FS.analyzePath(dir).exists) mod.FS.mkdirTree(dir);
      mod.FS.writeFile(name, u8.slice(contentStart, contentStart + size));
    }
    off += 512 + Math.ceil(size / 512) * 512;
  }
}

/** Fetch WDK teaching headers (ntddk.h etc.) into clang's in-memory FS. */
async function loadWdkHeadersInto(mod) {
  const manifest = await (await fetch(new URL("headers-manifest.json", DIST_URL))).json();
  for (const [vpath, b64] of Object.entries(manifest)) {
    const bin = atob(b64);
    const bytes = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
    const dir = vpath.split("/").slice(0, -1).join("/");
    if (dir && !mod.FS.analyzePath(dir).exists) mod.FS.mkdirTree(dir);
    mod.FS.writeFile(vpath, bytes);
  }
}

/** Fetch Linux 6.6.18 teaching headers into clang's FS (fallback stub if manifest missing). */
async function loadLinuxHeadersInto(mod) {
  // Prefer manifest if present (generated by tools/build-linux-sysroot.mjs)
  try {
    const res = await fetch(new URL("linux-headers-manifest.json", DIST_URL));
    if (res.ok) {
      const manifest = await res.json();
      for (const [vpath, b64] of Object.entries(manifest)) {
        const bin = atob(b64);
        const bytes = new Uint8Array(bin.length);
        for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
        const dir = vpath.split("/").slice(0, -1).join("/");
        if (dir && !mod.FS.analyzePath(dir).exists) mod.FS.mkdirTree(dir);
        mod.FS.writeFile(vpath, bytes);
      }
      return;
    }
  } catch {}
  // Fallback: try fetching tar (legacy sysroot)
  try {
    const tarUrl = new URL("sysroot-linux.tar", DIST_URL);
    const r = await fetch(tarUrl);
    if (r.ok) {
      const tarBuf = await r.arrayBuffer();
      const dec = new TextDecoder();
      const u8 = new Uint8Array(tarBuf);
      let off = 0;
      while (off + 512 <= u8.length) {
        const hdr = u8.slice(off, off + 512);
        const name = dec.decode(hdr.slice(0, 100)).replace(/\0.*$/, "");
        if (!name) break;
        const size = parseInt(dec.decode(hdr.slice(124, 136)).replace(/\0.*$/, "").trim(), 8) || 0;
        const contentStart = off + 512;
        if (size > 0 && !name.endsWith("/")) {
          const dir = name.split("/").slice(0, -1).join("/");
          if (dir && !mod.FS.analyzePath(dir).exists) mod.FS.mkdirTree(dir);
          mod.FS.writeFile(name, u8.slice(contentStart, contentStart + size));
        }
        off += 512 + Math.ceil(size / 512) * 512;
      }
      return;
    }
  } catch {}
  // Ultimate fallback: no external manifest — worker caller will use stub headers injected via compileToObjLinux's minimal FS writes
}

/** Compile C source -> x64 COFF object bytes (real clang, in-browser). */
async function compileToObj(source, target="windows") {
  const { clangMod: clang } = await getModules();
  const inName = "/work/driver.c";
  const outName = "/work/driver.obj";
  try {
    clang.FS.mkdirTree("/work");
    clang.FS.writeFile(inName, source);
    if (target === "linux") {
      await loadLinuxHeadersInto(clang);
      // If manifest missing, inject minimal stub headers directly
      const stubHeaders = {
        "/linux/include/linux/module.h": `#pragma once\n#define __init\n#define __exit\n#define __user\n#define MODULE_LICENSE(x)\nstruct module; extern struct module __this_module; #define THIS_MODULE (&__this_module)\n#define module_init(fn) int init_module(void) __attribute__((alias(#fn)))\n#define module_exit(fn) void cleanup_module(void) __attribute__((alias(#fn)))\nint printk(const char *fmt, ...);`,
        "/linux/include/linux/types.h": `#pragma once\ntypedef unsigned long size_t; typedef long loff_t; typedef long ssize_t;`,
      };
      for (const [p,c] of Object.entries(stubHeaders)) {
        try {
          const dir=p.split("/").slice(0,-1).join("/");
          if (dir && !clang.FS.analyzePath(dir).exists) clang.FS.mkdirTree(dir);
          if (!clang.FS.analyzePath(p).exists) clang.FS.writeFile(p,c);
        } catch {}
      }
      const code = clang.callMain([
        "--target=x86_64-linux-gnu",
        "-O1", "-ffreestanding", "-fno-stack-protector", "-fno-pic", "-mno-red-zone", "-mcmodel=kernel",
        "-isystem", "/linux/include",
        "-D__KERNEL__", "-DMODULE",
        "-c", inName, "-o", outName,
      ]);
      if (code !== 0) return { ok: false, error: "linux compilation failed (see stderr)" };
      const obj = clang.FS.readFile(outName, { encoding: "binary" });
      return { ok: true, obj };
    } else {
      await loadWdkHeadersInto(clang);
      const code = clang.callMain([
        "--target=x86_64-pc-windows-msvc",
        "-O1", "-ffreestanding", "-fno-stack-protector",
        "-isystem", "/wdm/include",
        "-c", inName, "-o", outName,
      ]);
      if (code !== 0) return { ok: false, error: "compilation failed (see stderr)" };
      const obj = clang.FS.readFile(outName, { encoding: "binary" });
      return { ok: true, obj };
    }
  } catch (e) {
    return { ok: false, error: String(e?.message ?? e) };
  }
}

self.onmessage = async (ev) => {
  const { id, op, payload } = ev.data ?? {};
  try {
    if (op === "compile") {
      const target = payload.target || "windows";
      const res = await compileToObj(payload.source, target);
      if (!res.ok) {
        self.postMessage({ id, ok: false, error: res.error });
        return;
      }
      self.postMessage({ id, ok: true, objBytes: res.obj });
    } else if (op === "warmup") {
      await getModules();
      self.postMessage({ id, ok: true });
    }
  } catch (e) {
    self.postMessage({ id, ok: false, error: String(e?.message ?? e) });
  }
};
